version: '1'

services:

  app:
    build: ./CRUDPruebas
    image: prueba/docker-jenkins-app

  unit:
    image: maven
    volumes:
      - .:/usr/src/myapp
      - /tmp/go:/go
    command: bash -c "mvn test"
